use_frameworks!

platform :ios, '12.0'

inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

target 'LVBlankTemplate_Example' do
  pod 'LVBlankTemplate', :path => '../'

  target 'LVBlankTemplate_Tests' do
    inherit! :search_paths

      pod 'AFNetworking','4.0.1'#swift:Alamofire
      pod 'DZNEmptyDataSet', '1.8.1'
      #pod 'FCUUID', '1.3.1'
      pod 'FFPopup', '~> 1.1.5'
      pod 'FMDB', '~> 2.7.5'
      pod 'Masonry', '1.1.0'
      pod 'MBProgressHUD', '~> 1.2.0'
      pod 'MJExtension', '~> 3.4.1'
      pod 'MJRefresh', '3.7.5'
      pod 'OpenUDID', '1.0.0'
      pod 'UICKeyChainStore', '2.2.1'
      #pod 'WebViewJavascriptBridge'#,'6.0.3'
      pod 'SDWebImage' , '~> 5.17.0'
      pod 'Toast', '~> 4.0.0'
      pod 'TYCyclePagerView', '1.2.0'
      pod 'YYModel', '1.0.4'
      pod 'LookinServer', :configurations => ['Debug']
      
      
  end
end
